### ISSUE TITLE
Los artículos no tienen ID ni otra forma de identidad única.

### ISSUE THREAD

**Issue by VictorPato** [DCC-CC4401/2018-1-SQL-Injection-T4#2]

**Comment by dsalazarl** [comment]
@VictorPato veo que los artículos sí tienen ID... o te referías a que, por ejemplo, en el django-admin no se están mostrando con su ID, u otra cosa?

![articles id](https://user-images.githubusercontent.com/12741709/43987084-6636b4b6-9ce9-11e8-9179-49ee79a5e1dd.PNG)

**Comment by VictorPato** [comment]
No se muestran en el django-admin, ni en las fichas, ni se puede buscar por id (requerimiento).
