### ISSUE TITLE
Las personas naturales no pueden realizar reservas de espacios desde la App.

### ISSUE THREAD

**Issue by dsalazarl** [DCC-CC4401/2018-1-SQL-Injection-T4#5]
La grilla muestra los espacios reservados, y pendientes, pero no se pueden seleccionar las casillas de horarios disponibles para reservar los espacios disponibles, ergo las personas naturales no pueden realizar reservas de espacios desde la app (sólo se puede desde el django-admin).

**Comment by VictorPato** [comment]
A que requerimiento está ligada esta issue? Fue requerimiento para la entrega anterior o es para esta entrega?

**Comment by dsalazarl** [comment]
@VictorPato corresponde al requisito 6, solicitado para la tarea 4.
